### ISSUE TITLE
#feature - Add new fields to sign up form

### ISSUE THREAD

**Issue by martinb214** [fovecsernyes/pizza-ordering-system#10]
Now there are only username and password fields on the sign up page, but there should be some other too, such as: 

- First and last name

- Age

- Home address

- Phone number

Please add these there and investigate how to store them in a DB (or how Django does this). According to GDPR we need to store these informations securely.

**Comment by martinb214** [comment]
Find me about security aspects of this issue when you are working on it.

**Comment by fovecsernyes** [comment]
the sign up page will not be modified, but the profile page after login.
