### ISSUE TITLE
#ui - Create frontend to the new user authentication pages

### ISSUE THREAD

**Issue by martinb214** [fovecsernyes/pizza-ordering-system#11]
Please create unified look to user authentication pages. You can change the text fields and buttons' label there too.

**Comment by fovecsernyes** [comment]
validation should **not** be done here. the following htmls should have style (css):

signup.html
login.html
password_reset_complete.html
password_reset_confirm.html
password_reset_done.html
password_reset_form.html

**Comment by fovecsernyes** [comment]
Can you give me some feedback about your progress? This issue is still in the "To do" column on the board.

**Comment by vattila96** [comment]
I will start working on it today.

**Comment by fovecsernyes** [comment]
How is your progress?

**Comment by fovecsernyes** [comment]
Do you need help with it?

**Comment by vattila96** [comment]
Will be done until tomorrow afternoon.

**Comment by fovecsernyes** [comment]
@vattila96 will you be able to finish it this weekend?

**Comment by fovecsernyes** [comment]
Or if it is done, please create a pull request called 'feature/11'
