### ISSUE TITLE
Collect user stories

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#13]
Please collect and create user stories based on what we discussed in the class.

It should look like the following statement:

- " As a user i want to register a new user and log in, and log out."

- "As an admin i want to upload new pizzas to the database."

**Comment by martonur** [comment]
Helpful articles for deeper understanding:
https://www.freecodecamp.org/news/how-and-why-to-write-great-user-stories-f5a110668246/
https://www.atlassian.com/agile/project-management/user-stories

**Comment by fovecsernyes** [comment]
legyszi mozgasd a boardon a taskot: https://github.com/fovecsernyes/pizza-ordering-system/projects/1

**Comment by fovecsernyes** [comment]
+ kerlek beszelj a sracokkal, akik ezen dolgoznak: https://github.com/fovecsernyes/pizza-ordering-system/issues/6 , hogy ne legyen kavarodas. Pl a my ordershez a design mar megvan.

**Comment by Aldius** [comment]
[User Story Document.docx](https://github.com/fovecsernyes/pizza-ordering-system/files/3723564/User.Story.Document.docx)

Elkészítettem a Business oldali user storykat. :)

**Comment by fovecsernyes** [comment]
A masik oldali storyk is kesz lesznek? koszi
