### ISSUE TITLE
#architecture - Docker-compose refactor

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#2]
Please check and refactor the docker compose file, if needed.

**Comment by fovecsernyes** [comment]
@martonur kell segitseg?

**Comment by fovecsernyes** [comment]
az lenne a legjobb, ha az app minden modositas utan ujratoltene, hogy gyorsabb legyen a fejlesztes.

**Comment by martonur** [comment]
I've mounted the source code to the Docker container, this way it automatically updates the web app upon page refresh, you don't have to rebuild the whole image.

**Comment by martonur** [comment]
The separation of the docker-compose file and image building is done, now Docker won't try to rebuild the image every time the containers are started. (it also solves the dangling image problem, untagged images won't be present anymore) 

If starting the app for the first time or after making changes in the Dockerfile the possibility to rebuild the image is given by the rebuild_images.sh script.

IMO the Docker infrastructure is working properly in its present form, if new feature requests or problems come up in the future, they should be handled in a new issue.
