### ISSUE TITLE
#ui - Navbar style

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#25]
Please make navigation bar stylish.

**Comment by martinb214** [comment]
And please do not forget to make the navigaton bar's references consistent (e.g., Pizzas vs Sign up). You can copy a popular website's navbar style here.

**Comment by fovecsernyes** [comment]
> And please do not forget to make the navigaton bar's references consistent (e.g., Pizzas vs Sign up). You can copy a popular website's navbar style here.

@martinb214 means that the Pizzas menu is a button and Sign up is a link, not a button. These should be consistent.

**Comment by martinb214** [comment]
Reviewed and tested, small changes are needed:
-Please autosquash fixup commits
-Navbar is not responsive (tested in Safari and Mozilla Firefox)
