### ISSUE TITLE
#database - implement entities

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#26]
Please add the designed entites to the app so we can use them. 

- The basline schema can be found here: https://github.com/fovecsernyes/pizza-ordering-system/issues/5

- The usage can be found here: https://github.com/fovecsernyes/pizza-ordering-system/issues/4

ps: on the admin page (user: admin, password: password) the entities can be checked: http://localhost:8000/admin/app/

**Comment by fovecsernyes** [comment]
check this pr for more info: https://github.com/fovecsernyes/pizza-ordering-system/pull/36

**Comment by atesztoth** [comment]
Thanks m8. Will take a look at it whenever I happen to have some 🗽time

**Comment by fovecsernyes** [comment]
Can you give me some feedback about your progress? This issue is still in the "To do" column on the board.

**Comment by atesztoth** [comment]
Tomorrow m8. Its s6urday

**Comment by atesztoth** [comment]
Amugy tenyleg bocsi hogy kesek vele. Holnap foglalkozok ezzel. A problema hogy mindig van mivel...

**Comment by fovecsernyes** [comment]
Did you get the neccessary infos?

**Comment by atesztoth** [comment]
now yes. pizza for you m8
