### ISSUE TITLE
#feature - Login/sign up validation

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#27]
Please add validation for the following pages:

signup.html
login.html

**Comment by fovecsernyes** [comment]
contact @martinb214 if neccessary.

**Comment by fovecsernyes** [comment]
Can you give me some feedback about your progress? This issue is still in the "To do" column on the board.

**Comment by fovecsernyes** [comment]
Will you be able to work on this task?

**Comment by Jugis** [comment]
Will be done on weekend

**Comment by fovecsernyes** [comment]
@Jugis will you be able to finish it this weekend?

**Comment by Jugis** [comment]
I won't be able to contribute any further I don't even have time for the course itself. Do not assign issues on me anymore sorry

**Comment by fovecsernyes** [comment]
Due date is around this Sunday (3rd on November). Please contact me if you have a hard time to finish. Thanks in advance.
