### ISSUE TITLE
#feature - implement frontend for Pizzas page

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#29]
Template can be found here: https://github.com/fovecsernyes/pizza-ordering-system/blob/master/design/pizzas.png

NOTE: the first entry should be clickable, which opens custom pizza creator page.

NOTE: please implement paginator, something like here: https://www.dev2qa.com/django-filter-and-pagination-example/

**Comment by fovecsernyes** [comment]
Is everything OK with this task?

**Comment by zolkol0077** [comment]
> Is everything OK with this task?

Yes, it will be finished soon.

**Comment by fovecsernyes** [comment]
@zolkol0077  if it is ready for a review, please open a pull request. if you need help with that feel free to contact me.

**Comment by fovecsernyes** [comment]
Can you correct the search bar? The paginator is not urgent.
