### ISSUE TITLE
#feature - Implement frontend for Home page

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#30]
Template can be found here: https://github.com/fovecsernyes/pizza-ordering-system/blob/master/design/homepage.png

**Comment by fovecsernyes** [comment]
Can you give me some feedback about your progress? This issue is still in the "To do" column on the board.

**Comment by fovecsernyes** [comment]
Will you be able to work on this task?

**Comment by fovecsernyes** [comment]
@ati008 if there is no interaction from you until midnight, i'll unassign this task from you.

**Comment by fovecsernyes** [comment]
Due date is around this Sunday (3rd on November). Please contact me if you have a hard time to finish. Thanks in advance.

**Comment by 96dervalics** [comment]
I can only do this on the weekend.
I have to do the html (with python)/css and connect the model to it?

**Comment by fovecsernyes** [comment]
@96dervalics weekend is okay. Just implement the frontend without backend (have a look at the closed frontend issues such as my orders and pizzas).
