### ISSUE TITLE
#feature - Customized pizza page

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#31]
please implement the customized pizza page based on https://github.com/fovecsernyes/pizza-ordering-system/blob/master/design/customize_pizza_modal.png

**Comment by fovecsernyes** [comment]
Can you give me some feedback about your progress? This issue is still in the "To do" column on the board.

**Comment by leaderhun** [comment]
I hope i will finish it today/tomorrow afternoon :)
