### ISSUE TITLE
#feature - integrate translation into navbar

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#33]
Please integrate translation to the navigation bar, so the user could set the language from every page. Adjust the urls if neccessary.

**Comment by fovecsernyes** [comment]
Can you give me some feedback about your progress? This issue is still in the "To do" column on the board.

**Comment by 96dervalics** [comment]
Its in progress. I forgot to move it.
I'll finish it tomorrow.

**Comment by fovecsernyes** [comment]
@96dervalics cool, thanks for the work. Please sync the current master, because a new navbar was added.
