### ISSUE TITLE
#backend - Database management

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#4]
Please investigate how we can use django with postgresql. The preferred method would be entities, because we dont want to control the database directly with sql scrips.

Please provide a working example.

**Comment by fovecsernyes** [comment]
@atesztoth meg tudnad nezni ezt? koszi

**Comment by atesztoth** [comment]
yes, de holnap fogok ra idot szanni

**Comment by fovecsernyes** [comment]
@atesztoth raersz amugy, csak most jutottam el odáig hogy osszehuzzam a taskokat :D

**Comment by atesztoth** [comment]
A dockerconfighoz lenne majd sok javaslatom, egy kis tuninggal egész használhatóvá lehetne tenni. Most minden changenél rebuildelni kell (ha dockerben akarod látni a változásokat ofc).

**Comment by atesztoth** [comment]
Ja látom már van rá egy PR. Zsír! Akkor nem csak engem zavart! :D

**Comment by fovecsernyes** [comment]
:D holnap mergelem majd

**Comment by fovecsernyes** [comment]
a gitignore nevu branchedet legyszi nevezd at feature/4-re es a ezzel a taskkal egyutt lehet majd mergelni

**Comment by atesztoth** [comment]
Törlöm. Benne lesz mint commit ebben is. 👍
