### ISSUE TITLE
#support - support development

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#49]
Since multiple collaborators will work on the backend tasks, I would like to ask you to help them if they need with the following:

- how to use entities (read, write etc.)
- how to send request to the backend
- how to respond to a frontend request
- how to handle responses
- how to update content based on the response
- help with the planning of the functionalities
- review their code before creating a PR

In this task you do not need to write any code, just give your support to make development faster and better.

**Comment by atesztoth** [comment]
🎉🎉

and respect Cashe

**Comment by martonur** [comment]
Hey m8, how can I add additional attributes to the Pizza class? I've found out that modifying the models.py file is not enough because it doesn't affect directly the database format and results in errors on both the pizzas and admin pizzas page.

**Comment by atesztoth** [comment]
Yo my testamentum! Migrations to the rescue! `python src/manage.py makemigrations` I guess.
Now unfortunately I dont have my mac with me so I cannot try it.
But here is some metal-food to chew on:
https://docs.djangoproject.com/en/2.2/topics/migrations/

**Comment by atesztoth** [comment]
_(I mean it seems to me that the problem is that you modify things in models but this does not propagate to the db since the driver does not gets informed about it.)_

**Comment by martonur** [comment]
Exactly, that's what I was missing, thanks for the support!!

**Comment by atesztoth** [comment]
> Exactly, that's what I was missing, thanks for the support!!

A man helps where he can. 🙏🏽

**Comment by Leriel9** [comment]
I need some help!
1. There isn't a relationship between Order and Address, so we don't actually know the billing address for each order.
2. Only the Transaction has an Amount field, so we can't show the price for each item. We only know the total sum.

I need to show these attributes for each order, for the 'My orders' page.
<details><summary>I tried changing the classes and then migrating the database, but I got the following error: </summary>
$ python src/manage.py makemigrations
Traceback (most recent call last):
  File "src/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\leven\AppData\Roaming\Python\Python27\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\leven\AppData\Roaming\Python\Python27\site-packages\django\core\management\__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "C:\Users\leven\AppData\Roaming\Python\Python27\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Users\leven\AppData\Roaming\Python\Python27\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\leven\AppData\Roaming\Python\Python27\site-packages\django\conf\__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Program Files (x86)\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named radixProject.settings
</details>

Help please!

**Comment by martonur** [comment]
> I need some help!
> 
> 1. There isn't a relationship between Order and Address, so we don't actually know the billing address for each order.
> 2. Only the Transaction has an Amount field, so we can't show the price for each item. We only know the total sum.
> 
> I need to show these attributes for each order, for the 'My orders' page.
> 
> I tried changing the classes and then migrating the database, but I got the following error:
> $ python src/manage.py makemigrations Traceback (most recent call last): File "src/manage.py", line 15, in execute_from_command_line(sys.argv) File "C:\Users\leven\AppData\Roaming\Python\Python27\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line utility.execute() File "C:\Users\leven\AppData\Roaming\Python\Python27\site-packages\django\core\management\__init__.py", line 308, in execute settings.INSTALLED_APPS File "C:\Users\leven\AppData\Roaming\Python\Python27\site-packages\django\conf\__init__.py", line 56, in __getattr__ self._setup(name) File "C:\Users\leven\AppData\Roaming\Python\Python27\site-packages\django\conf\__init__.py", line 41, in _setup self._wrapped = Settings(settings_module) File "C:\Users\leven\AppData\Roaming\Python\Python27\site-packages\django\conf\__init__.py", line 110, in __init__ mod = importlib.import_module(self.SETTINGS_MODULE) File "C:\Program Files (x86)\Python27\lib\importlib\__init__.py", line 37, in import_module __import__(name) ImportError: No module named radixProject.settings
> Help please!

I think you get this error because you are trying to run the migration script locally instead of in the container. Follow the instructions from this guide and I think you will be good to go:
https://phase2.github.io/devtools/common-tasks/ssh-into-a-container/
(after migration don't forget tot restart the containers)

**Comment by Leriel9** [comment]
Perfect, thank you!

**Comment by martonur** [comment]
Hey @atesztoth, can you explain it to me how models magically appear on the admin page? E.g. if I want to create a new model class, what do I have to do to be able to reach it from the admin page and create a new instance from it. Last time I tried to do that the new model sadly wasn't listed on the admin page.

**Comment by atesztoth** [comment]
Yes! It must be because you skipped one step. In my next comment you’re going to see the full answer.

**Comment by atesztoth** [comment]
Create you model in one of the two models.py, then in this file you must register it in order to have it appearing on the admin site: <root>/src/app/admin.py .
