### ISSUE TITLE
#database - Design baseline schema

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#5]
Please design the base schema for the database. Make a decision about what tables do we need and how should they connect.

Please create a diagram of the relations.

**Comment by Jugis** [comment]
@Leriel9 mai este elkezdem és felöltök egy Django Builder DB sémát. Ahogy nézem valami app generátor.

**Comment by fovecsernyes** [comment]
Légyszi majd a boardon is mozgassatok a taskot, és a branch neve feature/5 legyen (5az issue szama).

**Comment by fovecsernyes** [comment]
@Leriel9 @Jugis ez a task arrol szol, hogy a DB legyen megtervezve, @atesztoth -tal majd legyszi beszeljetek, mert a https://github.com/fovecsernyes/pizza-ordering-system/issues/4 task rajta van, ami meg arrol szol, hogy django-ban hogyan tudjuk effektiven hasznalni az adatbazis muveleteket.

**Comment by Jugis** [comment]
Csináltam brencset, és felcsekkoltam a domain/serialize fájlt, nézzetek rá.

Majd írok egy page-t amiben benne vannak a DB paramok magyarázatai.

**Comment by fovecsernyes** [comment]
legyszi nevezd at a branchet feature/5 -re (az 5 itt az issue szama) koszi.

**Comment by Jugis** [comment]
Done

**Comment by fovecsernyes** [comment]
ha ugy erzed kesz van, nyugodtan nyithatsz egy pr-t a masterbe, es legyszi adj egy rovid leirast, hogy hogyan lehet megnezni, hogy amit csinaltal, az mukodik. koszi

**Comment by Leriel9** [comment]
Nagyon jó lett a séma, viszont azt nem látom, hogy a felhasználók egyéni pizzáit melyik tábla tárolná.

**Comment by Jugis** [comment]
Mert azt elfelejtettem :D Ma módosítom és beadom a PR_t

**Comment by fovecsernyes** [comment]
@Jugis majd legyszi ird le hogy pontosan mit csinaltal ebben a taskban, es milyen fajlok hova kerultek, hogy egyszerubb legyen reviewezni. koszi

**Comment by fovecsernyes** [comment]
lesz ma PR?

**Comment by Jugis** [comment]
@Leriel9  nem tudnád befejezni esetleg?

**Comment by fovecsernyes** [comment]
@Leriel9 legyszi fejezd be, mert blokkolja a kovetkezo taskot ez az issue. koszi.
