### ISSUE TITLE
#feature - Tracking

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#51]
Please investigate and implement the easiest way to track a pizza order. The method is totally up to you, but it should work.

**Comment by zolkol0077** [comment]
Do we want to live track the Courier on the map or just stage of the food?

**Comment by fovecsernyes** [comment]
Up to you, but simple live track would be better.

**Comment by fovecsernyes** [comment]
Due date is around this Sunday (3rd on November). Please contact me if you have a hard time to finish. Thanks in advance.

**Comment by zolkol0077** [comment]
The frontend part is more or less finished but it needs some backend support:
- Need to add a POST endpoint to the backend where the couriers can post their positions with a body like this:

```
{
    "courierId" : "2",
    "long" : "47.492780",
    "lat" : "19.061503"
}
```
- Coordinates need to be returned to the frontend based on the `courierId - orderId - userId` connections.

ps.: where should I put this map?

**Comment by fovecsernyes** [comment]
consult https://github.com/fovecsernyes/pizza-ordering-system/issues/49 for a simple backend.

For now put it under "My Orders" somehow.

**Comment by zolkol0077** [comment]
This could be a feature on its own because the response has to be different in for every user based on the ordering number it's not a 5min craft in my opinion.

**Comment by fovecsernyes** [comment]
> This could be a feature on its own because the response has to be different in for every user based on the ordering number it's not a 5min craft in my opinion.

Okay, it will be new task

**Comment by fovecsernyes** [comment]
Can you open a pr for it if its done?

**Comment by zolkol0077** [comment]
The frontend part without backend data?

**Comment by fovecsernyes** [comment]
> The frontend part without backend data?

Yep

**Comment by fovecsernyes** [comment]
Please open a pull request at least for the frontend part.
