### ISSUE TITLE
#feature - Payment

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#52]
Please investigate and implement a DEMO paying site (for example OTP simplepay). It should be as simple as possible. 

Some useful sites:
- https://portal-sandbox.openbanking.otpbank.hu/#/
- https://www.simplepay.hu/fejlesztoknek

**Comment by fovecsernyes** [comment]
If you have problems with starting the app because the migration scripts, just run the 
```
./kill_app.sh
docker volume list
docker volume rm container_pgdata
```

code snippets.

**Comment by atesztoth** [comment]
all right man thanks!
