### ISSUE TITLE
#feature - create backend for Pizzas site

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#53]
Please create a backend for the pizzas site. The frontend should be also filled with data in this task. Since there are 3 assignees on this task, please share the work. If you need any help, do not hesitate to ask in this tasks: https://github.com/fovecsernyes/pizza-ordering-system/issues/49

**Comment by fovecsernyes** [comment]
Please wait until https://github.com/fovecsernyes/pizza-ordering-system/issues/29 is closed.

**Comment by fovecsernyes** [comment]
> Please wait until #29 is closed.

it is done

**Comment by martonur** [comment]
@fovecsernyes can you please add a more specific description of the task and the needed working functionalities?

**Comment by fovecsernyes** [comment]
@martonur 

- ~~If the user is not logged in, buy button should be inactive some way and tell the user to log in for ordering~~
- ~~The pizzas added by the admin on the admin page to the databese should be listed~~
- ~~Custom pizza creating should work, and after saving it should be displayed under create 'custom pizza' button. The saved custom pizza has an edit button.~~
- ~~Free text search should work~~
- allergene (check boxes at top) and pizza size/menu/dessert filtering should work
- Adding to the cart should work
- ~~It would be the best if shopping cart was a checkout popup (like create custom pizza), so the user could remove added entries or proceed to pay -> this also should work~~


for planning contact @atesztoth . the design contains additional infos (https://github.com/fovecsernyes/pizza-ordering-system/blob/master/design/pizzas.png) which can be helpful to you.

**Comment by fovecsernyes** [comment]
and feel free to modify the desing if neccessary.

**Comment by fovecsernyes** [comment]
Due date is around this Sunday (3rd on November). Please contact me if you have a hard time to finish. Thanks in advance.

**Comment by martonur** [comment]
As a first step I've started to work on displaying the pizzas added by the admin on the Pizzas page.

**Comment by martonur** [comment]
The pizzas from the database are now listed on the Pizzas page _(feature/53)_, started to work on the search function.

**Comment by fovecsernyes** [comment]
> The pizzas from the database are now listed on the Pizzas page _(feature/53)_, started to work on the search function.

Could you highlight somehow the content of my previous comment the parts that are done? Ty

**Comment by martonur** [comment]
> > The pizzas from the database are now listed on the Pizzas page _(feature/53)_, started to work on the search function.
> 
> Could you highlight somehow the content of my previous comment the parts that are done? Ty

Done.

**Comment by martonur** [comment]
The search function is now working as it should.

**Comment by martonur** [comment]
> @martonur
> 
> * If the user is not logged in, buy button should be inactive some way and tell the user to log in for ordering
> * ~The pizzas added by the admin on the admin page to the databese should be listed~
> * Custom pizza creating should work, and after saving it should be displayed under create 'custom pizza' button. The saved custom pizza has an edit button.
> * ~Free text search should work~
> * allergene (check boxes at top) and pizza size/menu/dessert filtering should work
> * Adding to the cart should work
> * It would be the best if shopping cart was a checkout popup (like create custom pizza), so the user could remove added entries or proceed to pay -> this also should work
> 
> for planning contact @atesztoth . the design contains additional infos (https://github.com/fovecsernyes/pizza-ordering-system/blob/master/design/pizzas.png) which can be helpful to you.

@martinb214 @botireal I've finished with the 2 crossed tasks, is it okay if I do the 5th task as my last in this issue? (allergene (check boxes at top) and pizza size/menu/dessert filtering should work
) Btw I'm starting to get the hang of the Django framework, feel free to ask if you feel stuck.

**Comment by martinb214** [comment]
Buy and Edit buttons' different behavior is done. Waiting for @botireal to choose his tasks. 

@fovecsernyes are you sure that we should implement shopping cart's functions in this issue? I think it is enough work (research and implementation) for an independent issue.

**Comment by botireal** [comment]
@martonur @martinb214  i've started to work on "custom pizza creating should work, and .."

**Comment by fovecsernyes** [comment]
> @fovecsernyes are you sure that we should implement shopping cart's functions in this issue? I think it is enough work (research and implementation) for an independent issue.

If you click on "Buy" (later it might be renamed to "Add to cart"), it should have an action (store the ordered pizza somewhere). Just simply write it to the shopping cart.

**Comment by martinb214** [comment]
Shopping cart as popup window is done. Developer could delete dummy content of popup window (commented part) while shopping cart's implementation.

**Comment by botireal** [comment]
Custom pizzas creating is done.

**Comment by martinb214** [comment]
Tried to working on it but I keep getting DB errors. Clean install (docker image rm and build_images) didn't solve the problem. I tried to find any solution but I'm not really a DB specialist so please inform me when these errors solved. Thx.

**Comment by fovecsernyes** [comment]
Will you be able to finish it this weekend? If you have problems contact @atesztoth .

**Comment by martinb214** [comment]
It depends on the DB. It's hard to do anything without a working website.

**Comment by fovecsernyes** [comment]
the database has been updated in master, please merge it to your branch to avoid conflicts.

**Comment by martonur** [comment]
@martinb214 try deleting every indexed file from src/app/migrations. 

The pizzas page and adding a pizza as admin is working for me after merging master to our branch, but for some reason I can't add a custom pizza on the Pizzas page.

IMO the allergen and food type filtering should be a new task which has to involve rewriting the models because atm they aren't well suited for our use case.

**Comment by fovecsernyes** [comment]
> @martinb214 try deleting every indexed file from src/app/migrations.
> 
> The pizzas page and adding a pizza as admin is working for me after merging master to our branch, but for some reason I can't add a custom pizza on the Pizzas page.
> 

@botireal please have a look at custom pizza creating.

> IMO the allergen and food type filtering should be a new task which has to involve rewriting the models because atm they aren't well suited for our use case.

ok, i'll create a new task for it.

@martinb214 if the solution above in not working, try to delete everyting using this: https://gist.github.com/beeman/aca41f3ebd2bf5efbd9d7fef09eac54d and clone the git directory again, if you are still not able to run it. it has solved the problem for me in an another task.

**Comment by martonur** [comment]
> > @martinb214 try deleting every indexed file from src/app/migrations.
> > The pizzas page and adding a pizza as admin is working for me after merging master to our branch, but for some reason I can't add a custom pizza on the Pizzas page.
> 
> @botireal please have a look at custom pizza creating.
> 
> > IMO the allergen and food type filtering should be a new task which has to involve rewriting the models because atm they aren't well suited for our use case.
> 
> ok, i'll create a new task for it.
> 
> @martinb214 if the solution above in not working, try to delete everyting using this: https://gist.github.com/beeman/aca41f3ebd2bf5efbd9d7fef09eac54d and clone the git directory again, if you are still not able to run it. it has solved the problem for me in an another task.

Custom pizza creation is working now, but note that it's not connected to the database yet, we have to first agree on what attributes should pizzas and all the other model classes have.

**Comment by martinb214** [comment]
After following @martonur's instructions to a working Pizzas page I keep getting DB error:
`django.db.utils.ProgrammingError: column app_pizza.size does not exist`. I see a commit to solve this error but it does not work for me.
I can start working on further features when after a clean install everything works smoothly and there is no need for hacking and workarounds...

**Comment by fovecsernyes** [comment]
@martinb214 remove the db volume listed with "docker volume list".
