### ISSUE TITLE
#feature - create backend for My Orders site

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#54]
Please create a backend for My Orders site. The frontend should be also filled with data in this task. If you need any help, do not hesitate to ask in this tasks: https://github.com/fovecsernyes/pizza-ordering-system/issues/49

**Comment by fovecsernyes** [comment]
Due date is around this Sunday (3rd on November). Please contact me if you have a hard time to finish. Thanks in advance.

**Comment by Leriel9** [comment]
I've done what I could, but there are some problems regarding this task.

1. There isn't a relationship between Order and Address, so we don't actually know the billing address for each order. (Right know I just take the last created Address.)
2. Only the Transaction has an Amount field, so we can't show the price for each item. We only know the total sum.

Nevertheless I created feature/54 branch and uploaded my code.

**Comment by fovecsernyes** [comment]
> I've done what I could, but there are some problems regarding this task.
> 
> 1. There isn't a relationship between Order and Address, so we don't actually know the billing address for each order. (Right know I just take the last created Address.)
> 2. Only the Transaction has an Amount field, so we can't show the price for each item. We only know the total sum.
> 
> Nevertheless I created feature/54 branch and uploaded my code.

Ask for help here: https://github.com/fovecsernyes/pizza-ordering-system/issues/49
