### ISSUE TITLE
#feature - Implement backend for Profile page

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#62]
Please implement backend functionality for Profile page.

- The user has to be able to save the data to database
- Please remove credit card information
- The user has to be able to add/edit/remove location

**Comment by fovecsernyes** [comment]
If you have problems with starting the app because the migration scripts, just run the 
```
./kill_app.sh
docker volume list
docker volume rm container_pgdata
```

code snippets.

**Comment by martinb214** [comment]
Task is implemented, ready for testing. Unfortunately I had to delete the already done fronted on Profile page because that has constant data. We should reopen the frontend related issue for this page.
