### ISSUE TITLE
#feature - accessibility

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#63]
Please do a research and implement a method to help people with disabilities to use the website. This task should include the following:

- Set a different color scheme
- The ability to enlarge the fonts.

Please add a button/slider or something like that to the frontend.

**Comment by fovecsernyes** [comment]
The css will be provided in this task: https://github.com/fovecsernyes/pizza-ordering-system/issues/68

**Comment by fovecsernyes** [comment]
If you have problems with starting the app because the migration scripts, just run the 
```
./kill_app.sh
docker volume list
docker volume rm container_pgdata
```

code snippets.

**Comment by zolkol0077** [comment]
Pushed changes to https://github.com/fovecsernyes/pizza-ordering-system/pull/76.
I need some feedback if I went in the right way.
Either way, I still need to make changes in the code.
