### ISSUE TITLE
#Bugfixing - Pizzas page

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#64]
The pizzas page has some bugs, please fix them:

- ~~When creating a custom pizza, the changing between topping and bases/sauces does not work. It works when editing.~~

- ~~A reset button is missing from the search input. Now the user has to do an empty search to clear the filtering.~~

- ~~The admin should have the possibility to add a picture to the pizza when creating on the admin site.~~

**Comment by fovecsernyes** [comment]
If you have problems with starting the app because the migration scripts, just run the 
```
./kill_app.sh
docker volume list
docker volume rm container_pgdata
```

code snippets.

**Comment by botireal** [comment]
All points of the issue (reset button, picture adding, custom creation) are done.
