### ISSUE TITLE
#design - general

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#68]
The color scheme right now is not the best, and the customer wants us to improve it. Please create a design scheme and reimplement the css files to make the page look nice. It should have a light and a night mode (changing between them is not part of this task, it is a different issue.)

The customer asked us to change the yellow color to some darker blue.

**Comment by fovecsernyes** [comment]
The changing feature will be provided in this task: https://github.com/fovecsernyes/pizza-ordering-system/issues/63

**Comment by fovecsernyes** [comment]
If you have problems with starting the app because the migration scripts, just run the 
```
./kill_app.sh
docker volume list
docker volume rm container_pgdata
```

code snippets.

**Comment by fovecsernyes** [comment]
do you have any progress?

**Comment by leaderhun** [comment]
> do you have any progress?

oops, i totally forgot about it. I will finish it on wednesday

**Comment by fovecsernyes** [comment]
@leaderhun do you have any progress on this one?

**Comment by fovecsernyes** [comment]
Still have not heard of your progress. Is there anything new?
