### ISSUE TITLE
#security - Setting up SSL to the website

### ISSUE THREAD

**Issue by martinb214** [fovecsernyes/pizza-ordering-system#7]
Secure the website with HTTPS.

**Comment by fovecsernyes** [comment]
Szükségünk van erre?

**Comment by fovecsernyes** [comment]
mivel dockerben hostoljuk jelenleg, ezert kesobb fogunk vele foglalkozni.

**Comment by fovecsernyes** [comment]
we dont need ssl in the docker so i am closing this issue
