### ISSUE TITLE
#feature - menu design

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#8]
Please decide what menus do we need and implement a template for it. 

We need clickable menus, which redirect to hello world-like pages. The order of the menus and the title of it is totally up to you. We need something like 'Home', 'My orders' etc.

**Comment by fovecsernyes** [comment]
a branch neve majd legyszi feature/8 legyen.

**Comment by martinb214** [comment]
Reviewed and tested changes, requirements talked directly with @botireal.

**Comment by martinb214** [comment]
Changes made by @botireal, everything ok, ticket is ready to merge.
