### ISSUE TITLE
Create backend for pizza tracking

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#84]
Please create backend for live pizza tracking.

**Comment by zolkol0077** [comment]
Please ask a backend developer for it.
Every information that is needed can be found here https://github.com/fovecsernyes/pizza-ordering-system/issues/51#issuecomment-549162432

**Comment by fovecsernyes** [comment]
I am asking you to do it, because there is no "backend" developer. If you need any help, please ask in our facebook group. Simply a random generated position based on time or whatever is enough. So it will look like the delivery guy is moving.

**Comment by zolkol0077** [comment]
I see a list of 5 people on our facebook group who registered themself as a backend developer at the project start. 
I am not qualified for this task. Your "seek for help" idea would work in a way that I ask somebody to do it for me but I am not the guy who assign tasks to people. There is no point of start learning how to do any stuff in python just for one task like this at the end of the project.

**Comment by fovecsernyes** [comment]
project is finished for now so closing this task
