### ISSUE TITLE
#feature - translation

### ISSUE THREAD

**Issue by fovecsernyes** [fovecsernyes/pizza-ordering-system#9]
Please investigate and implement traslation feature for the website. We need hungarian and english languages.

We need a button that changes the language, and an example in the code, which can be reused. The following tutorial can be helpful: https://youtu.be/xI97sLMd1rM

**Comment by fovecsernyes** [comment]
@96dervalics kell segitseg ebben?

**Comment by 96dervalics** [comment]
@fovecsernyes a video alapjan meglesz szerintem.

**Comment by fovecsernyes** [comment]
mikorra varhato, hogy befejezitek?

**Comment by fovecsernyes** [comment]
meg legyszi mozgassatok a boardon a taskot: https://github.com/fovecsernyes/pizza-ordering-system/projects/1

**Comment by 96dervalics** [comment]
én töltöttem fel feature/9 branch-re megoldást (példával)
view-ba: 
{% load i18n %} kell 
és {% trans "Magyar szöveg..." %} szerint fordít, 
a nyelvváltoztató gomb benne van a commitba (pizzexample.html).

máshol: 
from django.utils.translation import gettext as _ 
szerint test_translate = _("(teszt fordítás)") fordít

a settings.py és az urls.py -ben kell módosítani hogy ez működjön

tettem bele egy .po , .mo fájlt a src/locale/en/LC_MESSAGES/ -ba, csak a példa kedvéért, ha minden igaz a **django-admin makemessages -l en** -el létrehozná a .po fájlt ebbe a mappába, és a **django-admin compilemessages** paranccsal lefordítaná .mo -ra de ez nekem nem működött (django-admin nem létezik) , ezért poedit-tel csináltam.

magyar lenne az oldalt alapból és angolra fordítana (jelenleg így állítottam be)?

**Comment by fovecsernyes** [comment]
@96dervalics igen, magyar lenne alapbol. ha kesz van, nyitsz egy pull requestet? (ha kell segitseg szolj nyugodtan)
